const projects = [
  {
    id: 1,
    url: 'portfolio',
    img: '/projects/portfolio/thumb.png',
    title: 'Portfolio',
    type: "Website",
    icon: "/projects/portfolio/home.webp",
    github: 'https://github.com/EvanderInacio/Portfolio',
    web: 'https://evander.vercel.app/',
    description: 'Meu portfólio criado com o objetivo de mostrar meus projetos ao longo da minha carreira.',
    tags: [
      {name: "Next JS", icon: '/skills/next-js.svg' },
      {name: "TypeScript", icon: '/skills/typescript.svg' },
      {name: "Styled Components", icon: '/skills/styled-components.svg' },
    ],
    print: [
      {name: 'Thumb', img:'/projects/portfolio/thumb.png'},
      {name: 'About', img:'/projects/portfolio/about.png'},
      {name: 'Skills', img:'/projects/portfolio/skills.png'},
      {name: 'Projects', img:'/projects/portfolio/projects.png'},
      {name: 'Contact', img:'/projects/portfolio/contact.png'},
      {name: 'Detail-1', img:'/projects/portfolio/detail-1.png'},
      {name: 'Detail-2', img:'/projects/portfolio/detail-2.png'},
      {name: 'Detail-3', img:'/projects/portfolio/detail-3.png'},
      {name: 'Detail-4', img:'/projects/portfolio/detail-4.png'},
    ],
    backgroundImage: '/projects/portfolio/thumb.png',
    video: 'https://www.youtube.com/watch?v=8Ek_BFSi8Pk&t=2s&ab_channel=EvanderIn%C3%A1cio'
  },
  {
    id: 2,
    url: 'turtle-movie',
    img: '/projects/turtlemovie/turtle.png',
    title: 'Turtle Movie',
    type: "Website",
    icon: "/projects/turtlemovie/icon.png",
    github: 'https://github.com/EvanderInacio/Turtle-Movie',
    web: 'https://turtle-movie.vercel.app/',
    description: 'Website usando a API TMDB para fazer a listagem de filmes e series com as melhores notas da semana/dia, além de trazer as obras populares e também com as maiores notas da plataforma da TMDB. Podendo ver detalhes das obras, como Lançamento da obra, duração no caso de filmes, produção, idioma além do pais de origem. Ainda conta com uma listagem de atores populares com a opção de consultar os filmes que determinada pessoa participou.',
    tags: [
      {name: "React Js", icon: '/skills/react.svg' },
      {name: "React Router", icon: '/skills/react-router.svg' },
      {name: "TypeScript", icon: '/skills/typescript.svg' },
      {name: "Styled Components", icon: '/skills/styled-components.svg' },
    ],
    print: [
      {name: 'Movie', img:'/projects/turtlemovie/turtle-movie.png'},
      {name: 'Movie-Popular', img:'/projects/turtlemovie/movie-popular.png'},
      {name: 'Series-Popular', img:'/projects/turtlemovie/series-popular.png'},
      {name: 'Detail', img:'/projects/turtlemovie/detail-home.png'},
      {name: 'Detail-elenco', img:'/projects/turtlemovie/detail-elenco.png'},
      {name: 'Detail-video', img:'/projects/turtlemovie/detail-video.png'},
      {name: 'Peoples', img:'/projects/turtlemovie/peoples.png'},
      {name: 'Detail-people', img:'/projects/turtlemovie/detail-people.png'},
    ],
    backgroundImage: '/projects/turtlemovie/detail-home.png',
    video: 'https://www.youtube.com/watch?v=wt2g4q2md9g&ab_channel=EvanderIn%C3%A1cio'
  },
  {
    id: 3,
    url: 'playstation',
    img: '/projects/playstation/playstation.webp',
    title: 'PlayStation',
    type: "Website",
    icon: "/projects/playstation/icon.svg",
    github: 'https://github.com/EvanderInacio/PlayStation',
    web: 'https://playstation-4.vercel.app/',
    description: 'E-commerce Website da PlayStation para vendas de controles.',
    tags: [
      {name: "Html", icon: '/skills/html.svg' },
      {name: "Css", icon: '/skills/css.svg' },
      {name: "JavaScript", icon: '/skills/javascript.svg' },
    ],
    print: [
      {name: 'Home', img:'/projects/playstation/playstation-home.png'},
      {name: 'Home-2', img:'/projects/playstation/playstation-home-2.png'},
      {name: 'About', img:'/projects/playstation/playstation-about.png'},
      {name: 'Product', img:'/projects/playstation/playstation-product.png'},
      {name: 'Product-2', img:'/projects/playstation/playstation-product-2.png'},
      {name: 'Buy', img:'/projects/playstation/playstation-buy.png'},
      {name: 'Contact', img:'/projects/playstation/playstation-contact.png'},      
    ],
    backgroundImage: '/projects/playstation/playstation-home.png',
    video: 'https://www.youtube.com/watch?v=VZsm-NGse6M&ab_channel=EvanderIn%C3%A1cio'
  },
  {
    id: 4,
    url: 'podcastr',
    img: '/projects/podcastr/podcastr-home.png',
    title: 'Podcastr',
    type: "Website",
    icon: "/projects/podcastr/icon.svg",
    github: 'https://github.com/EvanderInacio/Podcastr',
    web: 'https://podcastr-evander.vercel.app/',
    description: 'Podcastr é uma plataforma construída para transmissão de podcast.',
    tags: [
      {name: "React JS", icon: '/skills/react.svg' },
      {name: "TypeScript", icon: '/skills/typescript.svg' },
      {name: "Next JS", icon: '/skills/next-js.svg' },
      {name: "Sass", icon: '/skills/sass.svg' },
    ],
    print: [
      {name:'Home', img:'/projects/podcastr/podcastr-home.png'},
      {name:'Home-2', img:'/projects/podcastr/podcastr-home-2.png'},    
      {name:'Detail', img:'/projects/podcastr/podcastr-detail.png'},       
    ],
    backgroundImage: '/projects/podcastr/podcastr-home.png',
    video: 'https://www.youtube.com/watch?v=a_OoBSceC80&ab_channel=EvanderIn%C3%A1cio'
  },
  {
    id: 5,
    url: 'github-blog',
    img: '/projects/github-blog/github-blog-home.png',
    title: 'Github Blog',
    type: "Website",
    icon: "/projects/github-blog/logo.svg",
    github: 'https://github.com/EvanderInacio/Github-Blog',
    web: 'https://github-blog-evander.vercel.app/',
    description: 'Github Blog utiliza a Api do Github para pegar os dados de usuário, e para puxar dados das issues desse repositório para transformar em postagens.',
    tags: [
      {name: "Next JS", icon: '/skills/next-js.svg' },
      {name: "TypeScript", icon: '/skills/typescript.svg' },
      {name: "Stitches", icon: '/skills/stitches.svg' },
    ],
    print: [
      {name: 'Home', img:'/projects/github-blog/github-blog-home.png'},
      {name: 'Home-2', img:'/projects/github-blog/github-blog-home-2.png'},
      {name: 'Detail', img:'/projects/github-blog/github-blog-detail.png'},
      {name: 'Detail-2', img:'/projects/github-blog/github-blog-detail-2.png'},
    ],
    backgroundImage: '/projects/github-blog/github-blog-home.png',
    video: 'https://www.youtube.com/watch?v=RcKQNz0n6Ts&ab_channel=EvanderIn%C3%A1cio'
  },
  {
    id: 6,
    url: 'whatsapp',
    img: '/projects/whatsapp/login.png',
    title: 'WhatsApp',
    type: "Website",
    icon: "/projects/whatsapp/icon.svg",
    github: 'https://github.com/EvanderInacio/WhatsApp',
    web: 'https://whatsapp-green.vercel.app/',
    description: 'Clone do WhatsApp web, usando o firebase (auth e firestore) para armazenar os dados de usuários e conversas, com a opção de dark mode para alterar o tema.',
    tags: [
      {name: "React JS", icon: '/skills/react.svg' },
      {name: "Styled Components", icon: '/skills/styled-components.svg' },
      {name: "Firebase", icon: '/skills/firebase.svg' },
    ],
    print: [
      {name: 'Login', img:'/projects/whatsapp/login.png'},
      {name: 'Home-light', img:'/projects/whatsapp/home-light.png'},
      {name: 'Home-dark', img:'/projects/whatsapp/home-dark.png'},
      {name: 'Chat', img:'/projects/whatsapp/chat.png'},
      {name: 'Chat-emoji', img:'/projects/whatsapp/chat-emoji.png'},
      {name: 'New-chat', img:'/projects/whatsapp/new-chat.png'},

    ],
    backgroundImage: '/projects/whatsapp/home-dark.png',
    video: 'https://www.youtube.com/watch?v=PZpp2sCm0zY&t=11s&ab_channel=EvanderIn%C3%A1cio'
  },
  {
    id: 7,
    url: 'pomodoro',
    img: '/projects/pomodoro/pomodoro-home.png',
    title: 'Pomodoro Timer',
    type: "App",
    icon: "/projects/pomodoro/timer.png",
    github: 'https://github.com/EvanderInacio/Pomodoro-Timer',
    web: 'https://pomodoro-timer-evander.vercel.app/',
    description: 'Pomodoro, o objetivo deste aplicativo é ajudá-lo a se concentrar em qualquer tarefa em que esteja trabalhando, como estudar, escrever ou codificar. Este aplicativo é inspirado na Técnica Pomodoro, que é um método de gerenciamento de tempo desenvolvido por Francesco Cirillo.',
    tags: [
      {name: "React JS", icon: '/skills/react.svg' },
      {name: "Styled Components", icon: '/skills/styled-components.svg' },
      {name: "TypeScript", icon: '/skills/typescript.svg' },
      {name: "React-hook-form", icon: '/skills/react-hook-form.svg' },
    ],
    print: [
      {name: 'Login', img:'/projects/pomodoro/pomodoro-home.png'},
      {name: 'Home-light', img:'/projects/pomodoro/pomodoro-home-action.png'},
      {name: 'Home-dark', img:'/projects/pomodoro/pomodoro-history.png'},
      {name: 'Chat', img:'/projects/pomodoro/pomodoro-history-2.png'},

    ],
    backgroundImage: '/projects/pomodoro/pomodoro-home.png',
    video: 'https://www.youtube.com/watch?v=c6fEo2CYj0k&ab_channel=EvanderIn%C3%A1cio'
  },
  {
    id: 8,
    url: 'pokedex',
    img: '/projects/pokedex/pokedex-home.png',
    title: 'Pokedex',
    type: "Website",
    icon: "/projects/pokedex/logo.svg",
    github: 'https://github.com/EvanderInacio/Pokedex',
    web: 'https://pokedex-evander.vercel.app/',
    description: 'O projeto consiste em uma plataforma web que tem como funcionalidade listar todos os Pokémons e exibir seus atributos. Todos os dados sobre os pokémons foram obtidos através da PokéApi.',
    tags: [
      {name: "Next JS", icon: '/skills/next-js.svg' },
      {name: "TypeScript", icon: '/skills/typescript.svg' },
      {name: "Styled Components", icon: '/skills/styled-components.svg' },
    ],
    print: [
      {name: 'Home', img:'/projects/pokedex/pokedex-index.png'},
      {name: 'Home-2', img:'/projects/pokedex/pokedex-home.png'},
      {name: 'Detail', img:'/projects/pokedex/pokedex-detail.png'},
      {name: 'Detail-2', img:'/projects/pokedex/pokedex-detail-about.png'},
      {name: 'Detail-3', img:'/projects/pokedex/pokedex-detail-stats.png'},
    ],
    backgroundImage: '/projects/pokedex/pokedex-index.png',
    video: 'https://www.youtube.com/watch?v=gWCbt85ltto&ab_channel=EvanderIn%C3%A1cio'
  },
]

export default projects