const educations = [
  {
    id: 1,
    title: 'Análise e Desenvolvimento de Sistemas',
    subTitle: 'Universidade Unopar',
    status: 'Completo',
    level: 'Superior',
    link: 'https://www.unopar.com.br/',
    description: 'O curso superior de Análise e Desenvolvimento de Sistemas - foca no desenvolvimento e no planejamento de sistemas de automação e de informação. ',
    logo: '/education/logos/unopar.png',
  },
  {
    id: 2,
    title: 'JavaScript e TypeScript',
    subTitle: 'Udemy',
    status: 'Andamento',
    level: 'Profissionalizante',
    link: 'udemy.com/course/curso-de-javascript-moderno-do-basico-ao-avancado/',
    description: 'Aprenda Javascript moderno (ES6+), TypeScript para front-end (com Webpack, babel, React, React Hooks, Redux, HTML5, CSS3 e mais) e back-end (com Node, Express, MySQL / MariaDB, MongoDB, PostgreSQL, Next.Js, Strapi e mais) e se torne um(a) desenvolvedor(a) full stack. ',
    logo: '/education/logos/udemy.svg',
  },
  {
    id: 3,
    title: 'React.Js e Next.Js',
    subTitle: 'Udemy',
    status: 'Planejamento',
    level: 'Profissionalizante',
    link: 'https://www.udemy.com/course/curso-de-reactjs-nextjs-completo-do-basico-ao-avancado/',
    description: 'Curso de React.Js + Next.Js completo do básico ao avançado. Aprenda ReactJS, NextJS, Styled-Components, testes com Jest e Testing Library, Storybook, Server-Side Rendering e demais siglas (SSR, SSG, ISR, CSR, SPA, PWA, etc...) no front-end. Aprenda, também, Strapi para criarmos APIs de back-end.',
    logo: '/education/logos/udemy.svg',
  },
  {
    id: 4,
    title: 'Conectar',
    subTitle: 'Rocketseat',
    status: 'Completo',
    level: 'Profissionalizante',
    link: 'https://rocketseat.com.br/',
    description: 'Você vai construir os primeiros conhecimentos sobre programação e tecnologia. Desde a diferenciação entre hardware e software, internet e seu papel no desenvolvimento, até o pensamento computacional e lógico, passando por tipos de aplicações web e linguagem de programação. ',
    logo: '/education/logos/rocketseat.svg',
  },
  {
    id: 5,
    title: 'Fundamentar',
    subTitle: 'Rocketseat',
    status: 'Completo',
    level: 'Profissionalizante',
    link: 'https://rocketseat.com.br/',
    description: 'No Fundamentar, você vai construir suas primeiras aplicações, e se tornará capaz de codar soluções funcionais para dar os primeiros passos na sua carreira.',
    logo: '/education/logos/rocketseat.svg',
  },
  {
    id: 6,
    title: 'Especializar',
    subTitle: 'Rocketseat',
    status: 'Completo',
    level: 'Profissionalizante',
    link: 'https://rocketseat.com.br/',
    description: 'Especializar, você vai ter seu primeiro contato com algumas soluções da programação web que são usadas diariamente no ambiente de trabalho, você vai ter seu primeiro contato e vai aprender como construir APIs do zero no back-end e como consumir APIs já existentes utilizando Fetch e Axios.',
    logo: '/education/logos/rocketseat.svg',
  },
  {
    id: 7,
    title: 'Lógica de Programação',
    subTitle: 'Fundação Bradesco',
    status: 'Completo',
    level: 'Profissionalizante',
    link: 'https://www.ev.org.br/',
    description: 'Curso de Lógica de Programação, para isso, são apresentados os fundamentos básicos da lógica da programação e as principais técnicas para o desenvolvimento de algoritmos: descrição narrativa, fluxograma e pseudocódigo.',
    logo: '/education/logos/bradesco.svg',
  },

]

export default educations